#page title
page_title                                : Cinopsys - Movie & TV Show Manager         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :  1234567890                               # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

patreon_link                              : https://www.patreon.com/cinopsys          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.cinopsys.movieshows                                          # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : ../assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Cinopsys - Movie & TV Show Manager         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Simple, elegant & completely free TRAKT client for Movies 🎥 & Shows 📺. No Ads!
enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Kashish Sharma                            
your_link                                 : https://www.linkedin.com/in/kashish98/                     
your_city                                 : India 🇮🇳                                
email_address                             : kashish25798@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : kashish25798
github_username                           : Kashish-Sharma
# youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Stay in sync
    description                           : Whether you add movies and shows to your Watchlist, History or Collection, they will always be synced back to your Trakt account.
    fontawesome_icon_name                 : sync-alt
    
  - title                                 : Discover
    description                           : Browse tons of movies and shows from categories like “Trending”, “Popular”, “Anticipated”, …
                                            Couldn't find the one you were looking for? The search bar will be with you. Always!
    fontawesome_icon_name                 : search

  - title                                 : All the details you've ever wanted
    description                           : Score, release date, runtime, genres, overview, casting, seasons, episodes, … Know everything about every movie and show!
    fontawesome_icon_name                 : info-circle

  - title                                 : Join our Discord server
    description                           : Want to discuss about movies and shows, report a bug, suggest a feature or just chat? Join our <a href="https://discord.gg/uSTkdmr">Discord</a>.
    fontawesome_icon_name                 : discord
    
  - title                                 : Want more?
    description                           : Send us your ideas to “kashish25798@gmail.com”.
    fontawesome_icon_name                 : lightbulb
  
#   - title                                 : Feature List
#     description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
#     fontawesome_icon_name                 : star

#   - title                                 : Smart App Banner
#     description                           : Display a smart app banner on iOS devices.
#     fontawesome_icon_name                 : arrow-alt-circle-down

#   - title                                 : Social Links
#     description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
#     fontawesome_icon_name                 : link

#   - title                                 : FontAwesome Support
#     description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
#     fontawesome_icon_name                 : info-circle

#   - title                                 : # New Feature Title
#     description                           : # New Feature Description
#     fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
